"""Build include/native_aprs_huffman_table.h from the free text of both local corpora.

Every byte value gets a code; lengths are limited to 15 bits by flattening
the frequencies. The table is part of the format: regenerate only on purpose,
and regenerate the test vectors with it.
"""
import collections
import heapq
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import native_tool
from roundtrip import f4mlv10, n7uv

MAX_BITS = 15
HEADER = Path(__file__).resolve().parents[2] / 'include' / 'native_aprs_huffman_table.h'


def lengths_for(freq):
    heap = [(f, s, (s,)) for s, f in enumerate(freq)]
    heapq.heapify(heap)
    depth = [0] * 256
    tie = 256
    while len(heap) > 1:
        f1, _, a = heapq.heappop(heap)
        f2, _, b = heapq.heappop(heap)
        for s in a + b:
            depth[s] += 1
        tie += 1
        heapq.heappush(heap, (f1 + f2, tie, a + b))
    return depth


def main():
    freq = collections.Counter()
    for text in native_tool.free_text(list(f4mlv10()) + list(n7uv())):
        freq.update(text)
    base = [freq[s] for s in range(256)]
    add = 1
    while True:
        lengths = lengths_for([f + add for f in base])
        if max(lengths) <= MAX_BITS:
            break
        add *= 2
    assert abs(sum(2 ** -l for l in lengths) - 1) < 1e-9
    rows = ''.join('        ' + ', '.join(f'{l:2d}' for l in lengths[i:i + 16]) + ',\n' for i in range(0, 256, 16))
    HEADER.write_text(
        '// Generated by tools/native_aprs/gen_huffman.py; do not edit.\n'
        '// Canonical Huffman code lengths for the free text of native LoRa APRS\n'
        '// frames, one entry per byte value, at most 15 bits.\n'
        '#ifndef NATIVE_APRS_HUFFMAN_TABLE_H_\n#define NATIVE_APRS_HUFFMAN_TABLE_H_\n\n'
        '#include <cstdint>\n\nnamespace NATIVE_APRS {\n\n'
        '    static const uint8_t HUFFMAN_LENGTHS[256] = {\n' + rows + '    };\n\n}\n\n#endif\n')
    print('max length', max(lengths), 'flattening', add)


if __name__ == '__main__':
    main()
